library(devtools)
load_all()

document()
check_man()

test()
test(filter = "engine_hybrid")
test(filter = "engine_rcpp")
test(filter = "evaluate")
test(filter = "examples")
test(filter = "fit$")
test(filter = "fit_utils")
test(filter = "fit_xy")
test(filter = "formula")
test(filter = "fuzzy_system")
test(filter = "metrics")
test(filter = "model")
test(filter = "params")
test(filter = "parsnip")
test(filter = "predict")
test(filter = "preprocess")
test(filter = "rcpp_df_convert")
test(filter = "rcpp_fuzzy_coco")
test(filter = "rcpp_list_convert")
test(filter = "rcpp_modules")
test(filter = "systematic")
test(filter = "^utils")

check()
run_examples()
