library(devtools)
load_all()

document("Rfuzzycoco")

test("Rfuzzycoco")
test("Rfuzzycoco", "engine_hybrid")
test("Rfuzzycoco", "engine_rcpp")
test("Rfuzzycoco", "evaluate")
test("Rfuzzycoco", "fit$")
test("Rfuzzycoco", "fit_utils")
test("Rfuzzycoco", "fit_xy")
test("Rfuzzycoco", "formula")
test("Rfuzzycoco", "fuzzy_system")
test("Rfuzzycoco", "metrics")
test("Rfuzzycoco", "model")
test("Rfuzzycoco", "params")
test("Rfuzzycoco", "parsnip")
test("Rfuzzycoco", "predict")
test("Rfuzzycoco", "preprocess")
test("Rfuzzycoco", "rcpp_df_convert")
test("Rfuzzycoco", "rcpp_fuzzy_coco_parsnip")
test("Rfuzzycoco", "rcpp_fuzzy_system")
test("Rfuzzycoco", "rcpp_list_convert")
test("Rfuzzycoco", "rcpp_modules")
test("Rfuzzycoco", "rcpp_rng")
test("Rfuzzycoco", "samples")
test("Rfuzzycoco", "systematic")

check("Rfuzzycoco")
