# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

df_convert <- function(df) {
    .Call(`_Rfuzzycoco_df_convert`, df)
}

lst_convert <- function(lst) {
    .Call(`_Rfuzzycoco_lst_convert`, lst)
}

rcpp_fuzzy_coco_eval <- function(df, fuzzy_system_desc, params, verbose = FALSE) {
    .Call(`_Rfuzzycoco_rcpp_fuzzy_coco_eval`, df, fuzzy_system_desc, params, verbose)
}

rcpp_fuzzy_coco_predict <- function(df, fuzzy_system_desc, verbose = FALSE) {
    .Call(`_Rfuzzycoco_rcpp_fuzzy_coco_predict`, df, fuzzy_system_desc, verbose)
}

rcpp_fuzzy_coco_searchBestFuzzySystem <- function(df, nb_out_vars, params, seed = 123L, verbose = FALSE) {
    .Call(`_Rfuzzycoco_rcpp_fuzzy_coco_searchBestFuzzySystem`, df, nb_out_vars, params, seed, verbose)
}

